"""empty message

Revision ID: 2c81f0bd43a6
Revises: 
Create Date: 2020-03-10 11:02:54.412499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c81f0bd43a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('animalID', sa.Integer(), nullable=False),
    sa.Column('startWeight', sa.Float(), nullable=True),
    sa.Column('w1', sa.Float(), nullable=True),
    sa.Column('w2', sa.Float(), nullable=True),
    sa.Column('w3', sa.Float(), nullable=True),
    sa.Column('w4', sa.Float(), nullable=True),
    sa.Column('finalWeight', sa.Float(), nullable=True),
    sa.Column('motherID', sa.Integer(), nullable=True),
    sa.Column('fatherID', sa.Integer(), nullable=True),
    sa.Column('diet', sa.Text(), nullable=True),
    sa.Column('ch4_daily_mean', sa.Float(), nullable=True),
    sa.Column('feedEfficiency', sa.Float(), nullable=True),
    sa.Column('waterEfficieny', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('animalID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('animals')
    # ### end Alembic commands ###
